### Exercice 1: Factorisation LU mise en pratique

1)  Calculer la factorisation $LU$ de la matrice $A$ :

$$A=\begin{pmatrix}
1&1&1\\
2&2&5\\
4&6&8
\end{pmatrix}.$$

2) Même question pour la matrice $\tilde{A}$ :

$$\tilde{A}=\begin{pmatrix}1&1&1\\
2&2+10^{-6}&5\\
4&6&8
\end{pmatrix}.$$


**Correction**:
    
**Question 1)**:

$$\mbox{det}\left(A^{(2)}\right)
=\mbox{det}\begin{pmatrix}
1&1\\
2&2
\end{pmatrix}=0$$

Une des sous matrices n'est pas inversible, donc la décomposition LU n'existe pas.

**Question 2)**:

$$\mbox{det}\left(A^{(1)}\right)=1\neq 0,
\mbox{det}\left(A^{(2)}\right)
=\mbox{det}\begin{pmatrix}
1&1\\
2&2+10^6
\end{pmatrix}=10^6$$

et

$$\mbox{det}\left(A^{(3)}\right)=\mbox{det}A
=\mbox{det}\begin{pmatrix}1&1&1\\
2&2+10^{-6}&5\\
4&6&8
\end{pmatrix}$$

$$=1\times(2+10^{-6})\times8+2\times6\times1+4\times1\times5-4\times(2+10^{-6})\times1-6\times5\times1-8\times2\times1$$

$$=16+8\times10^{-6}+12+20-8-4\times10^{-6}-30-16=-6+4\times10^{-6}\neq 0$$

Donc la décomposition LU existe.

$$\begin{array}{rcl}
\begin{pmatrix}1&1&1\\
2&2+10^{-6}&5\\
4&6&8
\end{pmatrix}
&\underset{\begin{array}{c}L_2\rightarrow L_2-2L_1\\L_4\rightarrow L_3-4L_3\end{array}}{\longrightarrow}&
\begin{pmatrix}1&1&1\\
0&10^{-6}&3\\
0&2&4
\end{pmatrix}\\
&\underset{L_3\rightarrow L_3-2\times 10^{6}L_2}{\longrightarrow}&
\begin{pmatrix}1&1&1\\
0&10^{-6}&3\\
0&0&4-6\times 10^6
\end{pmatrix}\\
\end{array}$$

Donc $L=\begin{pmatrix}1&0&0\\
2&1&0\\
4&2\times 10^6&1
\end{pmatrix}$ 
et $U=\begin{pmatrix}1&1&1\\
0&10^{-6}&3\\
0&0&4-6\times 10^6
\end{pmatrix}$.

### Exercice 2 (implémentation Python) : Précision de la méthode

1) Calculer les factorisations LU de la matrice $A$ pour plusieurs valeurs de $p>0$ : 
    
$$A=\begin{pmatrix}1&1&1\\
2&2+10^{-p}&5\\
4&6&8
\end{pmatrix}.$$

En python, on pourra s'aider de la fonction 


$\texttt{import}$ $\texttt{scipy}$ $\texttt{as}$ $\texttt{sc}$

$\texttt{sc.linalg.lu}$


2) A l'aide du conditionnement des matrices $L$ et $U$, conclure sur la précision des méthodes.


**Correction**:
    
**Question 1)**:

In [22]:
import numpy as np
import matplotlib.pyplot as plt
import scipy as sc
import scipy.linalg as scl

#for p in range(1,6):
A=np.array([[1., 1., 1.], [2., 2+10**(-6), 5.], [4., 6., 8.]])
P,L,U=scl.lu(A)
print(P)
print(L)
print(U)

[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
[[1.        0.        0.       ]
 [0.5       1.        0.       ]
 [0.25      0.5000005 1.       ]]
[[ 4.         6.         8.       ]
 [ 0.        -0.999999   1.       ]
 [ 0.         0.        -1.5000005]]


**2)**
$\frac{||\tilde{x}-x||}{||x||}\leq Cond(A)\frac{||\tilde{b}-b||}{||b||}\leq Cond(LU)\frac{||\tilde{b}-b||}{||b||}$

### Exercice 3 : Une autre factorisation

Soient $$A_1=\begin{pmatrix}
1&-2&0\\-2&8&-6\\
0&-6&25
\end{pmatrix} \text{ et }
A_2=\begin{pmatrix}
4&0&12&-6\\
0&1&2&1\\
12&2&49&-4\\
-6&1&-4&51
\end{pmatrix}.$$

Montrer que les matrices $A_1$ et $A_2$ peuvent s'écrire $A_i=B_iB_i^T$ avec $B_i$ une matrice triangulaire inférieure avec des éléments diagonaux strictement positifs.

_Indication : on pourra utiliser la décomposition LU de_ $A_i$ _ainsi que la matrice_ $D=\text{diag}(\sqrt{u_{1, 1}},\sqrt{u_{2, 2}}, ..., \sqrt{u_{n, n}})$. 

**Remarque.** Une telle décomposition est appelée la décomposition de Cholesky. La matrice $B$ existe (et est unique) dès que $A$ est symétrique définie positive.

**Correction**:

**1) Montrons que** $A_1$ **est définie positive:**

Pour tout $x\in\mathbb{R}^3$,

$$\begin{array}{rcl}<x, A_1x>=x^TA_1x
&=&\left(\begin{array}{ccc}x_1&x_2&x_3\end{array}\right)
\left(\begin{array}{c}x_1-2x_2\\-2x_1+8x_2-6x_3\\-6x_2+25x_3\end{array}\right)\\
&=&x_1^2-2x_1x_2-2x_1x_2+8x_2^2-6x_2x_3-6x_2x_3+25x^2_3\\
&=&x_1^2-4x_1x_2+8x_2^2-12x_2x_3+25x^2_3\\
&=&(x_1-2x_2)^2+4x_2^2-12x_2x_3+25x^2_3\\
&=&(x_1-2x_2)^2+(2x_2-3x_3)^2+16x^2_3>0
\end{array}$$
Donc $A_1$ est définie positive.




**Autre méthode :**

$$\mbox{det}\left(A^{(1)}_1\right)=1\neq 0,
\mbox{det}\left(A^{(2)}_1\right)
=\mbox{det}\begin{pmatrix}
1&-2\\
-2&8
\end{pmatrix}=4\neq 0$$
et
$$\mbox{det}\left(A^{(3)}_1\right)=\mbox{det}A
=1\times 8\times 25-(-2)\times (-2)\times 25-(-6)\times (-6)\times 1
=200-100-36=64\neq 0$$

Donc $A_1$ est bien symétrique définie positive.

**Décomposition de Cholesky :**
Appliquons la décomposition LU à $A_1$ :
$$\begin{array}{rcl}
A_1=\begin{pmatrix}
1&-2&0\\-2&8&-6\\
0&-6&25
\end{pmatrix}&
\underset{L2\rightarrow L_2+2L_1}{\longrightarrow}&
\begin{pmatrix}
1&-2&0\\0&4&-6\\
0&-6&25
\end{pmatrix}\\
&\underset{L3\rightarrow L_3+\frac{6}{4}L_2}{\longrightarrow}&
\begin{pmatrix}
1&-2&0\\0&4&-6\\
0&0&16
\end{pmatrix}
\end{array}$$


Donc $L=\begin{pmatrix}
1&0&0\\
-2&1&0\\
0&-\frac{3}{2}&1
\end{pmatrix}$ 
et $U=\begin{pmatrix}
1&-2&0\\0&4&-6\\
0&0&16
\end{pmatrix}$.

On pose $D=\mbox{diag}(1,2,4)$ et on remarque que $LD=B$ et $D^{-1}U=B^T$ avec

$$B=\begin{pmatrix}
1&0&0\\
-2&2&0\\
0&-3&4
\end{pmatrix}$$


**2) Montrons que** $A_2$ **est définie postive:**

Pour tout $x\in\mathbb{R}^4$,

$$\begin{array}{rcl}<x, A_2x>=x^TA_2x
&=&\left(\begin{array}{cccc}x_1&x_2&x_3&x_4\end{array}\right)
\left(\begin{array}{c}4x_1+12x_3-6x_4\\x_2+2x_3+x_4\\12x_1+2x_2+49x_3-4x_4\\-6x_1+x_2-4x_3+51x_4\end{array}\right)\\
&=&4x_1^2+12x_1x_3-6x_1x_4+x_2^2+2x_2x_3+x_2x_4+12x_1x_3+2x_3x_2+49x_3^2-4x_3x_4\\&&-6x_1x_4+x_2x_4-4x_4x_3+51x_4^2\\
&=&4x_1^2+24x_1x_3-12x_1x_4+x_2^2+4x_2x_3+49x_3^2-8x_3x_4+2x_2x_4+51x_4^2\\
&=&(2x_1+6x_3-3x_4)^2+(x_2+2x_3+x_4)^2+(3x_3+4x_4)^2+25x^2_4>0
\end{array}$$
Donc $A_2$ est définie positive.


**Autre méthode :**

$$\mbox{det}\left(A^{(1)}_2\right)=4\neq 0,
\mbox{det}\left(A^{(2)}_2\right)
=4\neq 0$$
$$\mbox{det}\left(A^{(3)}_2\right)=\mbox{det}A
=4\times 1\times 49-12\times 1\times 12-4\times 2\times 2
=196-144-16=142\neq 0$$
et
$$\mbox{det}\left(A^{(4)}_2\right)=\mbox{det}A
=900\neq 0$$

Donc $A_2$ est bien symétrique définie positive.

**Décomposition de Cholesky :**
Appliquons la décomposition LU à $A_2$

$$\begin{array}{rcl}
A_2=\begin{pmatrix}
4&0&12&-6\\
0&1&2&1\\
12&2&49&-4\\
-6&1&-4&51
\end{pmatrix}&
\underset{\begin{array}{c}L_3\rightarrow L_3-3L_1\\L_4\rightarrow L_4+\frac{6}{4}L_1\end{array}}{\longrightarrow}&
\begin{pmatrix}
4&0&12&-6\\
0&1&2&1\\
0&2&13&14\\
0&1&14&42
\end{pmatrix}\\
&\underset{\begin{array}{c}L_3\rightarrow L_3-2L_2\\L_4\rightarrow L_4-L_2\end{array}}{\longrightarrow}&
\begin{pmatrix}
4&0&12&-6\\
0&1&2&1\\
0&0&9&12\\
0&0&12&41
\end{pmatrix}\\
&\underset{L_4\rightarrow L_4-\frac{12}{9}L_3}{\longrightarrow}&
\begin{pmatrix}
4&0&12&-6\\
0&1&2&1\\
0&0&9&12\\
0&0&0&25
\end{pmatrix}
\end{array}$$

Donc $L=\begin{pmatrix}
1&0&0&0\\
0&1&0&0\\
3&2&1&0\\
-\frac32&1&\frac43&1
\end{pmatrix}$ 
et $U=\begin{pmatrix}
4&0&12&-6\\
0&1&2&1\\
0&0&9&12\\
0&0&0&25
\end{pmatrix}$.

On a $D=\mbox{diag}(2,1,3,5)$ et on remarque que $LD=B$ et $D^{-1}U=B^T$ avec

$$B=\begin{pmatrix}
2&0&0&0\\
0&1&0&0\\
6&2&3&0\\
-3&1&4&5
\end{pmatrix}$$


### Exercice 4 : Décomposition LU sans utiliser sc.linalg.lu

1) Construire une fonction **DecompositionLU(A)** qui calcule les matrices $L$ et $U$ de la décomposition $LU$ de la matrice $A$.

2) Appliquer cette fonction aux matrices 
$$A_1=\begin{pmatrix}
9&8&6\\
7&6&12\\
9&3&9
\end{pmatrix} \text{ et }A_2=\begin{pmatrix}
11&8&3&13\\
2&12&7&10\\
3&3&17&13\\
11&2&12&7
\end{pmatrix}.$$
Les réponses attendues pour $U$ par exemple sont
$$U_1=\begin{pmatrix}
9&8&6\\
0&-\frac{2}{9}&\frac{22}{3}\\
0&0&-162
\end{pmatrix} \text{ et }U_2=\begin{pmatrix}
11&8&3&13\\
0&10.5454545&6.45454545&7.63636364\\
0&0&15.6810345&8.86206897\\
0&0&0&-8.81693238
\end{pmatrix}.$$

3) Soient $A$ une matrice triangulaire inférieure et $x$ une solution du système $Ax=b$ (si cette solution existe). Ecrire une relation de récurrence pour calculer les $x_i$. Cette récurrence s'appelle **l'algorithme de descente.**

4) Écrire de même une relation de récurrence entre les $x_i$ si $A$ est une matrice trianguaire supérieure (on retrouve ainsi **l'algorithme de remontée**).

5) Construire une fonction **Descente(A,b)** correspondant à l'algorithme de descente.

6) Construire de même une fonction **Remontee(A,b)** correspondant à l'algorithme de remontée.

7) À l'aide des fonctions **DecompositionLU**, **Remontee** et **Descente**, écrire une fonction qui résoud un système linéaire $Ax=b$. L'utiliser pour les systèmes $A_1x=\begin{pmatrix}1\\1\\1\end{pmatrix}$ et $A_2x=\begin{pmatrix}1\\1\\1\\1\end{pmatrix}.$

8) Tester votre code. Vérifier votre programme en comparant la solution avec ce que fournit la fonction **np.linalg.solve(A,b)** de Python. 


**Correction**:

In [1]:
# ------------------------ question 1 -----------------------------
def DecompositionLU(A):
    n=np.shape(A)[0]
    
    # construction de L
    L=np.zeros((n,n))
            
    # construction de U (attention on modifie directement A donc il faut calculer L avant)
    for i in range(0,n):
        L[i,i]=1.
        for k in range(i+1,n):  # attention il faut commencer a i+1 !!
            L[k,i]=A[k,i]/A[i,i]
            A[k,0:n]=A[k,0:n]-A[k,i]/A[i,i]*A[i,0:n]
            
    U=np.copy(A)
    
    return L, U



In [5]:
# ------------------------ question 2 -----------------------------
A1=np.array([[9., 8., 6.], [7., 6., 12.], [9., 3., 9.]])
A2=np.array([[11., 8., 3., 13.], [2., 12., 7., 10.], [3., 3., 17., 13.], [11., 2., 12., 7.]])

L1, U1 = DecompositionLU(A1)
print("exo 6 = ", L1, U1)

L2, U2 = DecompositionLU(A2)
print("exo 6 = ", L2, U2)



('exo 6 = ', array([[ 1.        ,  0.        ,  0.        ],
       [ 0.77777778,  1.        ,  0.        ],
       [ 1.        , 22.5       ,  1.        ]]), array([[   9.        ,    8.        ,    6.        ],
       [   0.        ,   -0.22222222,    7.33333333],
       [   0.        ,    0.        , -162.        ]]))
('exo 6 = ', array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.18181818,  1.        ,  0.        ,  0.        ],
       [ 0.27272727,  0.07758621,  1.        ,  0.        ],
       [ 1.        , -0.56896552,  0.80813634,  1.        ]]), array([[11.        ,  8.        ,  3.        , 13.        ],
       [ 0.        , 10.54545455,  6.45454545,  7.63636364],
       [ 0.        ,  0.        , 15.68103448,  8.86206897],
       [ 0.        ,  0.        ,  0.        , -8.81693238]]))


In [2]:
# ------------------------ question 5 -----------------------------

def Descente(A, b):
    n=np.size(b)
    x=np.zeros(n)
    x[0]=b[0]/A[0,0]
    for i in range(1, n):
        S=np.sum(A[i,0:i]*x[0:i]) # operation terme a terme
        x[i]=(b[i]-S)/A[i,i]
    return x

"""
avec des boucles for :
    def Descente(A,b):
    n=A.shape[0]
    x=np.zeros(n)
    x[0]=b[0]/A[0,0]
    for k in range(1,n):
        for j in range(0,k):
            b[k]=b[k]-A[k,j]*x[j]
        x[k]=b[k]/A[k,k]
    return x
"""



'\navec des boucles for :\n    def Descente(A,b):\n    n=A.shape[0]\n    x=np.zeros(n)\n    x[0]=b[0]/A[0,0]\n    for k in range(1,n):\n        for j in range(0,k):\n            b[k]=b[k]-A[k,j]*x[j]\n        x[k]=b[k]/A[k,k]\n    return x\n'

In [7]:
# ------------------------ question 6 -----------------------------

def Remontee(A, b):
    n=np.size(b)
    x=np.zeros(n)
    x[n-1]=b[n-1]/A[n-1,n-1]
    for i in range(n-2, -1, -1):
        S=np.sum(A[i,i+1:n]*x[i+1:n]) # operation terme a terme
        x[i]=(b[i]-S)/A[i,i]
    return x

"""
avec des boucles for :
def Remontee(A,b):
    n=A.shape[0]
    x=np.zeros(n)
    x[n-1]=b[n-1]/A[n-1,n-1]
    for k in range(2, n+1):
        for j in range(n-1,n-k, -1):
            b[n-k]=b[n-k]-A[n-k,j]*x[j]
        x[n-k]=b[n-k]/A[n-k,n-k]
    return x
"""



'\navec des boucles for :\ndef Remontee(A,b):\n    n=A.shape[0]\n    x=np.zeros(n)\n    x[n-1]=b[n-1]/A[n-1,n-1]\n    for k in range(2, n+1):\n        for j in range(n-1,n-k, -1):\n            b[n-k]=b[n-k]-A[n-k,j]*x[j]\n        x[n-k]=b[n-k]/A[n-k,n-k]\n    return x\n'

In [8]:
# ------------------------ question 7 -----------------------------
def Resolution_generale(A, b):
    n=np.shape(A)[0]
    L, U = DecompositionLU(A)
    # on resout Ly=b
    y=Descente(L,b)
    # on resout Ux=y
    x=Remontee(U,y)
    return x


x1=Resolution_generale(A1, np.ones(3))
x2=Resolution_generale(A2, np.ones(4)) 



('exo 6 = ', 0.0)
('exo 6 = ', 2.7755575615628914e-17)


In [ ]:
# ------------------------ question 8 -----------------------------
x1_exact=np.linalg.solve(A1, np.ones(3))
x2_exact=np.linalg.solve(A2, np.ones(4))

erreur1=np.max(np.abs(x1-x1_exact))
erreur2=np.max(np.abs(x2-x2_exact))
print("exo 6 = ", erreur1)
print("exo 6 = ", erreur2)


### Exercice 5 : Matrice inversible

Soient $a, b, c$ et $d$ des nombres réels. On considère la matrice 
$A=\begin{pmatrix}a&a&a&a\\
a&b&b&b\\
a&b&c&c\\
a&b&c&d\\
\end{pmatrix}.$

1) Déterminer la décomposition $LU$ de $A$ (si elle existe).

2) Donner les conditions sur $a, b, c$ et $d$ pour que la matrice $A$ soit inversible.









**Correction**

**1)** Soit $A=\begin{pmatrix}a&a&a&a\\
a&b&b&b\\
a&b&c&c\\
a&b&c&d
\end{pmatrix}.$

On applique le pivot de Gauss
$$\begin{array}{rcl}
A=\begin{pmatrix}
a&b&b&b\\
a&b&c&c\\
a&b&c&d
\end{pmatrix}&
\underset{\begin{array}{c}L_2\rightarrow L_2-L_1\\L_3\rightarrow L_3-L_1\\L_4\rightarrow L_4-L_1\end{array}}{\longrightarrow}&
\begin{pmatrix}
a&a&a&a\\
0&b-a&b-a&b-a\\
0&b-a&c-a&c-a\\
0&b-a&c-a&d-a
\end{pmatrix}\\
&\underset{\begin{array}{c}L_3\rightarrow L_3-L_2\\L_4\rightarrow L_4-L_2\end{array}}{\longrightarrow}&
\begin{pmatrix}
a&a&a&a\\
0&b-a&b-a&b-a\\
0&0&c-b&c-b\\
0&0&c-b&d-b
\end{pmatrix}\\
&\underset{L_4\rightarrow L_4-L_3}{\longrightarrow}&
\begin{pmatrix}
a&a&a&a\\
0&b-a&b-a&b-a\\
0&0&c-b&c-b\\
0&0&0&d-c
\end{pmatrix}
\end{array}$$

Donc $L=\begin{pmatrix}
1&0&0&0\\
1&1&0&0\\
1&1&1&0\\
1&1&1&1
\end{pmatrix}$ 
et $U=\begin{pmatrix}
a&a&a&a\\
0&b-a&b-a&b-a\\
0&0&c-b&c-b\\
0&0&0&d-c
\end{pmatrix}$.
Donc la décomposition **LU** existe.

**2)** La matrice $A$ est inversible si et seulement si les matrices $L$ et $U$ le sont.

En tant que matrice triangulaires, elles le sont si et seulement si les termes de leurs diagonales sont non-nuls,
c'est-à-dire 

$$a\neq 0,b\neq a,c\neq b,d\neq c.$$

### Exercice 6 : (implémentation Python) : Matrice du laplacien

On rappelle que la matrice du laplacien est définie par 
$$A=\begin{pmatrix}
2&-1&&&0\\
-1&2&-1&&\\
&\ddots&\ddots&\ddots&\\
&&-1&2&-1\\
0&&&-1&2\\
\end{pmatrix}
$$

1) Comment déterminer l'inverse de $A$ à partir de la résolution de $Ax=b$ pour des vecteurs $b$ bien choisis ?

2) En prenant les vecteurs $b$ de la question précédente et à l'aide des fonctions **DecompositionLU**, **Remontee**
et **Descente** de l'exercice 6 calculer numériquement l'inverse de la matrice $A$ 
(sans utiliser la fonction **np.linalg.inv(A)**). 

3) Comparer le résultat avec ce que retourne **np.linalg.inv(A)**.





In [15]:
# ------------------------ question 1 -----------------------------
n=5

# construction de A et b
c = -1.*np.ones(n-1)
d = 2.*np.ones(n)
e = -1.*np.ones(n-1)
A= np.diag(c, -1) + np.diag(d,0) + np.diag(e, 1)

# on decompose A en L et U
L2,U2 = DecompositionLU(A)



In [ ]:
# ------------------------ question 2 -----------------------------
A_inv=np.zeros((n,n))
I=np.eye(n)
# on resout Ax=b pour b = e_j vecteur canonique 
for i in range(0,n):
    y2=Descente(L2,I[0:n,i])
    x2=Remontee(U2,y2)
    A_inv[0:n,i]=np.copy(x2)
    


In [16]:
# ------------------------ question 3 -----------------------------
c = -1.*np.ones(n-1)
d = 2.*np.ones(n)
e = -1.*np.ones(n-1)
A= np.diag(c, -1) + np.diag(d,0) + np.diag(e, 1)
# attention il faut redefinir A car LU modifie A

print("exo 8 = ", np.max(np.abs(A_inv-np.linalg.inv(A))))

('exo 8 = ', 1.1102230246251565e-16)
